services:
    alfredoramos.seometadata.listener:
        class: alfredoramos\seometadata\event\listener
        arguments:
            - '@config'
            - '@alfredoramos.seometadata.helper'
        tags:
            - { name: event.listener }

    alfredoramos.seometadata.acp.controller:
        class: alfredoramos\seometadata\controller\acp
        arguments:
            - '@config'
            - '@template'
            - '@request'
            - '@language'
            - '@user'
            - '@log'

    alfredoramos.seometadata.helper:
        class: alfredoramos\seometadata\includes\helper
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@template'
            - '@cache.driver'
            - '@user'
            - '@upload_imagesize'
            - '%core.root_path%'
            - '%core.php_ext%'
